# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 04:20
from __future__ import unicode_literals

import apps.images.models
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.images.models.Image.generate_filename, verbose_name='Image')),
            ],
            options={
                'db_table': 'images',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ImageContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'image_container',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='image',
            name='image_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.ImageContainer'),
        ),
    ]
