# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 06:15
from __future__ import unicode_literals

import apps.images.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0003_auto_20180220_0409'),
        ('chemical_analyses', '0004_auto_20180220_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.images.models.Image.generate_filename, verbose_name='Image')),
                ('version', models.IntegerField(default=0)),
                ('collector', models.CharField(blank=True, max_length=50)),
                ('public_data', models.BooleanField(default=False)),
                ('chemical_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='chemical_analyses.ChemicalAnalysis')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='ImageContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'image_container',
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.ImageContainer'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_type_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='images.ImageType'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='samples.Sample'),
        ),
        migrations.AddField(
            model_name='image',
            name='subsample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='samples.Subsample'),
        ),
    ]
