# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_type_id',
        ),
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='images.ImageType'),
        ),
    ]
