# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20180220_0409'),
        ('images', '0002_image_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='samples',
        ),
        migrations.AddField(
            model_name='image',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='samples.Sample'),
        ),
    ]
