# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20180220_0409'),
        ('images', '0003_auto_20180220_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='subsample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='samples.Subsample'),
        ),
    ]
