# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analyses', '0004_auto_20180220_0409'),
        ('images', '0004_image_subsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='chemical_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='chemical_analyses.ChemicalAnalysis'),
        ),
    ]
