# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180618_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetype',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
