# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180618_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='collector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
