# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20180619_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='images.Image', unique=True),
        ),
    ]
