# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_remove_image_chemical_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComments',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('version', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
            ],
            options={
                'db_table': 'image_comments',
            },
        ),
    ]
