# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_imagecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomments',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='images.Image'),
        ),
    ]
