# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20180827_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_image_id', models.IntegerField()),
                ('new_image_id', models.UUIDField()),
            ],
            options={
                'db_table': 'image_mapping',
            },
        ),
    ]
