# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_analyses', '0003_chemicalanalysis_stage_y'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemicalanalysis',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='oxide',
            options={'ordering': ['id']},
        ),
    ]
