# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20170425_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collector',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='georeference',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='metamorphicgrade',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='metamorphicregion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rocktype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subsample',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subsampletype',
            options={'ordering': ['id']},
        ),
    ]
